### add book
POST http://localhost:8000/api/v1/books
Content-Type: application/json

{
  "title": "地球往事I：三体",
  "author": "刘慈欣",
  "isbn": "978-7-5366-9293-0"
}

### get book with id 1
GET http://localhost:8000/api/v1/books/1
Accept: application/json

### list books
GET http://localhost:8000/api/v1/books
Accept: application/json

### list books, jwt enabled
GET http://localhost:8000/api/v1/books
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ3ODk5MzcsImlzcyI6IkJvb2tLZXkifQ.6J3djwHAFXYa91J_cb5t3EujKMNv00ysl70-F7cRYec

### get book with id 1, jwt enabled
GET http://localhost:8000/api/v1/books/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ3ODk5MzcsImlzcyI6IkJvb2tLZXkifQ.6J3djwHAFXYa91J_cb5t3EujKMNv00ysl70-F7cRYec

### list books, Basic Authentication enabled
### admin:admin -> Base64  -> YWRtaW46YWRtaW4=
GET http://localhost:8000/api/v1/books
Accept: application/json
Authorization: Basic dTE6dTE=


### list books, API Key enabled
### admin:admin -> Base64  -> YWRtaW46YWRtaW4=
GET http://localhost:8000/api/v1/books
Accept: application/json
apikey: ppm_test_key

### list books, Auth2.0 enabled
GET http://localhost:8000/api/v1/books
Accept: application/json
Authorization: bearer AnAhOub47g2AtosTYiipu3Ab7teazYtI


### Bot Detection enabled, blocked
GET http://localhost:8000/api/v1/books/1
Accept: application/json

### with UA, passed
GET http://localhost:8000/api/v1/books/1
Accept: application/json
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36



### Rate limit, allowing 1 request per second: API rate limit exceeded
### python C:\WorkSpace\TRAE\kong-integration-api\src\test\java\com\example\test\http\rate_limit_test.py
GET http://localhost:8000/api/v1/books/1
Accept: application/json
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36

### Request Termination enabled, 503 Service Temporarily Unavailable
GET http://localhost:8000/api/v1/books/1
Accept: application/json
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36



