server:
  port: 8080

spring:
  application:
    name: kong-integration-api
  datasource:
    url: jdbc:h2:mem:booksdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true